# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d3ef61fa64f4e7cd0a0ed2a2d15d6ec35ac2256601a4edb8d201610c00ff0197e44d5fc6d6586951351fbddd51c8e2dc20dac620a55bef93cddb9ba3949a27

test:
  secret_key_base: 5b4eca0262089deca04bc1982625e360f98f65e54f4b4fa89c84e1c4a14564cd2eb0324efdb9df2267ccec4cec7cbe325f395b42cf9609a5a46b744a5bb92c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
